spring.application.name=KitchensinkMordernization

server.servlet.context-path=/kitchensink/rest

spring.mongodb.uri=${MONGO_DB_URI}
spring.mongodb.database=kitchensink

spring.security.user.name=user

spring.security.user.password=ME

jwt.secretKey=dfwdhivbwf92w93ji8f32if3hvij3bervb3jiwgv93irg3irgb9u3rgv3rgv93uh

spring.data.mongodb.auto-index-creation=true
